// frontend/tailwind.config.js
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{ts,tsx,js,jsx}', './index.html'],
  theme: {
    extend: {
      colors: {
        'km-bg':       '#FAFAF8',
        'km-surface':  '#FFFFFF',
        'km-surface-2':'#F5F3EE',
        'km-border':   '#E8E4DC',
        'km-border-dark':'#C8C4BC',
        'km-text':     '#1A1714',
        'km-text-2':   '#5C5650',
        'km-text-3':   '#9C9890',
        'km-gold':     '#B8860B',
        'km-gold-light':'#D4A017',
        'km-gold-bg':  '#FBF6E9',
        'km-red':      '#C41E3A',
        'km-red-bg':   '#FFF0F0',
        'km-success':  '#2D6A4F',
        'km-error':    '#C41E3A',
        'km-admin-bg':    '#F7F5F0',
        'km-admin-surface': '#FFFFFF',
        'km-admin-sidebar': '#1A1714',
        'km-admin-sidebar-text': '#E8E4DC',
      },
      fontFamily: {
        'playfair': ['Playfair Display', 'serif'],
        'dm':       ['DM Sans', 'sans-serif'],
      },
      animation: {
        'fadeInUp':     'fadeInUp 0.6s ease both',
        'fadeInDown':   'fadeInDown 0.5s ease both',
        'fadeIn':       'fadeIn 0.4s ease both',
        'slideInRight': 'slideInRight 0.5s ease both',
        'slideInLeft':  'slideInLeft 0.5s ease both',
        'scaleIn':      'scaleIn 0.4s ease both',
        'float':        'float 3s ease-in-out infinite',
        'cartBounce':   'cartBounce 0.4s ease',
        'shimmer':      'shimmer 1.5s infinite',
        'pulse-gold':   'pulse-gold 2s ease-in-out infinite',
      },
      keyframes: {
        fadeInUp:     { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeInDown:   { from: { opacity: '0', transform: 'translateY(-24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeIn:       { from: { opacity: '0' }, to: { opacity: '1' } },
        slideInRight: { from: { opacity: '0', transform: 'translateX(40px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        slideInLeft:  { from: { opacity: '0', transform: 'translateX(-40px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        scaleIn:      { from: { opacity: '0', transform: 'scale(0.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        float:        { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-8px)' } },
        cartBounce:   { '0%, 100%': { transform: 'scale(1)' }, '30%': { transform: 'scale(1.3)' }, '60%': { transform: 'scale(0.9)' } },
        shimmer:      { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'pulse-gold': { '0%, 100%': { boxShadow: '0 0 0 0 rgba(184,134,11,0.3)' }, '50%': { boxShadow: '0 0 0 8px rgba(184,134,11,0)' } },
      },
      boxShadow: {
        'product': '0 4px 20px rgba(0,0,0,0.08)',
        'product-hover': '0 12px 40px rgba(0,0,0,0.14)',
        'nav': '0 2px 20px rgba(0,0,0,0.06)',
        'cart': '0 0 60px rgba(0,0,0,0.2)',
      },
    },
  },
  plugins: [],
};
